name: eduapp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  riverpod: any
  provider: ^6.1.1
  google_sign_in: ^5.0.0
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.0.0
  lottie: ^3.1.0
  flutter_svg: ^0.22.0
  image_picker: ^1.0.7
  sms_otp_auto_verify: ^2.1.0
  flutter_session_jwt: ^0.0.6
  pin_input_text_field: ^4.5.1
  table_calendar: ^3.1.1
  # flutter_web_socket: ^1.0.5
  # firebase_core: ^2.30.1
  # firebase_messaging: ^14.9.1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  # flutter_local_notifications: ^8.2.0
  intl: ^0.19.0
  capitalize: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins_SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf


